# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-01 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_num', models.IntegerField()),
                ('pat_num', models.IntegerField()),
                ('title', models.CharField(max_length=140)),
                ('inventor_first', models.CharField(max_length=140)),
                ('inventor_last', models.CharField(max_length=140)),
            ],
        ),
    ]
